### ISSUE TITLE
Submit a revere linked list code

### ISSUE THREAD

**Issue by manish831** [manish831/DSA#1]

**Comment by ghost** [comment]
**The function to reverse a linked list**


void reverse()
    {
        // Initialize current, previous and next pointers
        Node* current = head;
        Node *prev = NULL, *next = NULL;
 
        while (current != NULL) {
            // Store next
            next = current->next;
            // Reverse current node's pointer
            current->next = prev;
            // Move pointers one position ahead.
            prev = current;
            current = next;
        }
        head = prev;
    }

This fixes #1
